import React from 'react'
import Table from 'react-bootstrap/Table'

export default function oders() {
  return (
    <>
      <Table striped bordered hover>
        <thead>
          <tr>
            <th>#</th>
            <th>訂單編號</th>
            <th>顧客姓名</th>
            <th>訂購日期</th>
            <th>金額</th>
            <th>付款方式</th>
            <th>運送方式</th>
            <th>訂單狀態</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>1</td>
            <td>#1</td>
            <td>Jark</td>
            <td>2024/02/24</td>
            <td>390</td>
            <td>信用卡</td>
            <td>黑貓</td>
            <td>完成</td>
          </tr>
          <tr>
            <td>2</td>
            <td>#2</td>
            <td>Jark</td>
            <td>2024/03/16</td>
            <td>139</td>
            <td>貨到付款</td>
            <td>7-11</td>
            <td>未完成</td>
          </tr>
          <tr>
            <td>3</td>
            <td>#3</td>
            <td>Jark</td>
            <td>2024/03/18</td>
            <td>900</td>
            <td>信用卡</td>
            <td>黑貓</td>
            <td>完成</td>
          </tr>
          <tr>
            <td>4</td>
            <td>#4</td>
            <td>Jark</td>
            <td>2024/03/18</td>
            <td>1480</td>
            <td>信用卡</td>
            <td>黑貓</td>
            <td>完成</td>
          </tr>
          <tr>
            <td>5</td>
            <td>#5</td>
            <td>Jark</td>
            <td>2024/03/20</td>
            <td>590</td>
            <td>貨到付款</td>
            <td>7-11</td>
            <td>未完成</td>
          </tr>
          <tr>
            <td>6</td>
            <td>#6</td>
            <td>Jark</td>
            <td>2024/03/22</td>
            <td>277</td>
            <td>貨到付款</td>
            <td>全家</td>
            <td>未完成</td>
          </tr>
          <tr>
            <td>7</td>
            <td>#7</td>
            <td>Jark</td>
            <td>2024/03/22</td>
            <td>450</td>
            <td>貨到付款</td>
            <td>全家</td>
            <td>未完成</td>
          </tr>
          <tr>
            <td>8</td>
            <td>#8</td>
            <td>Jark</td>
            <td>2024/03/24</td>
            <td>1190</td>
            <td>信用卡</td>
            <td>黑貓</td>
            <td>完成</td>
          </tr>
        </tbody>
      </Table>
    </>
  )
}
