const Pty = [
  {
    id: 14,
    Image: require('@/public/images/product/list/p1.webp'),
    title: '新品上市',
    name: '醜娃娃:八寶的餅乾',
    price: 'NT$351',
  },
  {
    id: 15,
    Image: require('@/public/images/product/list/p2.webp'),
    title: '新品上市',
    name: '實話實說2 ',
    price: 'NT$390',
  },
  {
    id: 16,
    Image: require('@/public/images/product/list/p3.webp'),
    title: '新品上市',
    name: 'Turing Machine',
    price: 'NT$1190',
  },
  {
    id: 17,
    Image: require('@/public/images/product/list/p4.webp'),
    title: '新品上市',
    name: '璀璨寶石 Splendor ',
    price: 'NT$1400',
  },
  {
    id: 18,
    Image: require('@/public/images/product/list/p5.webp'),
    title: '新品上市',
    name: '甜點大胃王',
    price: 'NT$465',
  },
  {
    id: 19,
    Image: require('@/public/images/product/list/p6.webp'),
    title: '新品上市',
    name: '狐作非為 Outfoxed',
    price: 'NT$702',
  },
  {
    id: 20,
    Image: require('@/public/images/product/list/p7.webp'),
    title: '新品上市',
    name: '迴轉壽司 Sushi Go! ',
    price: 'NT$351',
  },
  {
    id: 21,
    Image: require('@/public/images/product/list/p8.webp'),
    title: '新品上市',
    name: '餅乾大戰',
    price: 'NT$450',
  },
  {
    id: 22,
    Image: require('@/public/images/product/list/p9.webp'),
    title: '新品上市',
    name: '醬醬三明治',
    price: 'NT$450',
  },
  {
    id: 23,
    Image: require('@/public/images/product/list/p10.webp'),
    title: '新品上市',
    name: '動物對對碰',
    price: 'NT$490',
  },
  {
    id: 24,
    Image: require('@/public/images/product/list/p12.webp'),
    title: '新品上市',
    name: '骰子街',
    price: 'NT$750',
  },
  {
    id: 25,
    Image: require('@/public/images/product/list/p13.webp'),
    title: '新品上市',
    name: '冰淇淋快手2.0',
    price: 'NT$465',
  },
  {
    id: 26,
    Image: require('@/public/images/product/list/p14.webp'),
    title: '新品上市',
    name: '蛋糕比薩捲餅帽',
    price: 'NT$308',
  },
  {
    id: 27,
    Image: require('@/public/images/product/list/p15.webp'),
    title: '新品上市',
    name: '妙語說書人',
    price: 'NT$888',
  },
]

export default Pty
